### ISSUE TITLE
issues after update to v1.1.1

### ISSUE THREAD

**Issue by supoeric** [danielwelch/hassio-zigbee2mqtt#103]
I got the following error after update to version1.1.1
zigbee2mqtt:info 2019-2-5 02:02:34 Connecting to MQTT server at mqtt://192.168.0.119:1883
/zigbee2mqtt-1.1.1/node_modules/q/q.js:155
                throw e;
                ^
TypeError: Cannot read property 'zigbeeModel' of undefined
    at devices.forEach (/zigbee2mqtt-1.1.1/lib/extension/coordinatorGroup.js:24:34)
    at Array.forEach (<anonymous>)
    at zigbee.getAllClients.forEach (/zigbee2mqtt-1.1.1/lib/extension/coordinatorGroup.js:23:21)
    at Array.forEach (<anonymous>)
    at CoordinatorGroup.onZigbeeStarted (/zigbee2mqtt-1.1.1/lib/extension/coordinatorGroup.js:22:37)
    at extensions.filter.forEach (/zigbee2mqtt-1.1.1/lib/controller.js:98:75)
    at Array.forEach (<anonymous>)
    at Controller.onZigbeeStarted (/zigbee2mqtt-1.1.1/lib/controller.js:98:58)
    at zigbee.start (/zigbee2mqtt-1.1.1/lib/controller.js:149:26)
    at shepherd.start (/zigbee2mqtt-1.1.1/lib/zigbee.js:64:17)
npm
 ERR! code
 ELIFECYCLE
npm 
ERR! errno 1
npm
 ERR! zigbee2mqtt@1.1.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

here is my configure:
{
  "data_path": "/share/zigbee2mqtt",
  "homeassistant": true,
  "permit_join": true,
  "mqtt_base_topic": "zigbee2mqtt",
  "mqtt_server": "mqtt://192.168.x.xxx:1883",
  "serial_port": "/dev/ttyACM1",
  "devices": [],
  "network_key": [],
  "zigbee_shepherd_devices": true
}

**Comment by danielwelch** [comment]
Are you using a custom devices file?

**Comment by BasSmeets** [comment]
I had the same issue, disabled custom devices file. Then re-enabled it again. That worked for me.
