### ISSUE TITLE
Loading configuration failed

### ISSUE THREAD

**Issue by flipreverse** [danielwelch/hassio-zigbee2mqtt#106]
Hi!

I just installed zigbee2mqtt-edge in Hass.IO, and it fails to start. (It also fails for zigbee2mqtt).
It tries to load its configurations file which causes an Python error. For details see below:
```
[Info] Configuration file found: /share/zigbee2mqtt/configuration.yaml
Traceback (most recent call last):
  File "set_config.py", line 159, in <module>
    main(args.options_path, args.data_path)
  File "set_config.py", line 106, in main
    cfg.set_option('homeassistant')
  File "set_config.py", line 16, in set_option
    if self.get_config(name, category) is not None:
  File "set_config.py", line 39, in get_config
    return self.config.get(config_name, None)
AttributeError: 'NoneType' object has no attribute 'get'
```
zigbee2mqtt's config file `/share/zigbee2mqtt/configuration.yaml` is always empty. If I add some lines, it gets truncated upon restart.
Here is my config for the Hass.IO addon:
```
{
  "data_path": "/share/zigbee2mqtt",
  "homeassistant": true,
  "permit_join": false,
  "mqtt_base_topic": "zigbee2mqtt",
  "mqtt_server": "mqtt://homeassistant",
  "serial_port": "/dev/ttyACM0",
  "devices": [],
  "network_key": [
    245,
    225,
    XXX,
    XXX,
    XXX,
    XXX,
    XXX,
    XXX,
    XXX,
    XXX,
    XXX,
    XXX,
    XXX,
    XXX,
    XXX,
    XXX
  ],
  "include_device_information": true,
  "log_level": "debug",
  "log_directory": "logs/",
  "channel": 20,
  "last_seen": "True",
  "overwrite": true
}
```

Cheers,
Alex

**Comment by flipreverse** [comment]
*EDIT*
After removing `"log_directory": "logs/"` everything works fine.
The `set_con.py` wasn't able to store `/share/zigbee2mqtt/logs` in the configuration file.
