### ISSUE TITLE
Addon fails to start after update to 1.2.1 with SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by janvde** [danielwelch/hassio-zigbee2mqtt#131]
The error I get when I try to start the addon:

```[Info] Configuration file found: /share/zigbee2mqtt/configuration.yaml
[Info] Configuration written to /share/zigbee2mqtt/configuration.yaml
/usr/lib/node_modules/pm2/node_modules/has-flag/index.js:3
SyntaxError: Invalid or unexpected token
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

My configuration:

```{
  "data_path": "/share/zigbee2mqtt",
  "homeassistant": true,
  "permit_join": false,
  "mqtt_base_topic": "zigbee2mqtt",
  "mqtt_server": "mqtt://localhost:1883",
  "serial_port": "/dev/ttyACM0",
  "devices": [],
  "network_key": [],
  "disable_led": true,
  "mqtt_user": "",
  "mqtt_pass": ""
}
```

**Comment by wimpie007** [comment]
update to 1.2.1 was also not successfull here.
No devices came available.
Just reverted to previous version and all was ok again. (hassio)
Will try again later.

**Comment by xmegapixelx** [comment]
I have v 1.1.1 still, put Mosquitto update also broke my setup. Is there any way to downgrade Mosquitto back to 4.0 if I don't have a backup?

**Comment by janvde** [comment]
I've just downgraded Mosquitto to 4.0, but the issue remains.

**Comment by riddertommie** [comment]
I think i have the same problem, after upgrading.  I reinstall Hassio rpi3 compleet again, but stil not working.

PS i'm on the 64 bits Version. and Mosquitto MQTT Server bundled with Hivemq's web client.

_____________________________________ Error below this line_______________________________________________

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-25T09_51_43_945Z-debug.log
2019-03-25T10:51:46: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2019-03-25T10:51:46: PM2 log: App [npm:0] starting in -fork mode-
2019-03-25T10:51:46: PM2 log: App [npm:0] online
> zigbee2mqtt@1.2.1 start /app
> node index.js
fs.js:115
    throw err;
    ^
Error: ENOENT: no such file or directory, open '/share/zigbee2mqtt/configuration.yaml'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at Object.readYaml (/app/lib/util/fs.js:5:29)
    at read (/app/lib/util/settings.js:116:18)
    at getSettings (/app/lib/util/settings.js:80:21)
    at Object.get (/app/lib/util/settings.js:286:52)
    at Object.<anonymous> (/app/lib/util/logger.js:10:24)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.2.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm 
ERR! Failed at the zigbee2mqtt@1.2.1 start script.
