### ISSUE TITLE
Addon fails to start with Parser Error: Unhandled 'error' event

### ISSUE THREAD

**Issue by soeren-k** [danielwelch/hassio-zigbee2mqtt#142]
This is the error I get when starting the plugin in Hassio:
```
2019-04-07T20:44:59.991Z zigbee-shepherd:request RSP <-- SYS:osalNvRead, status: 0
2019-04-07T20:45:00.013Z zigbee-shepherd:request REQ --> SAPI:readConfiguration
2019-04-07T20:45:00.048Z zigbee-shepherd:request RSP <-- SAPI:readConfiguration, status: 0
2019-04-07T20:45:00.059Z zigbee-shepherd:request REQ --> SAPI:readConfiguration
2019-04-07T20:45:00.091Z zigbee-shepherd:request RSP <-- SAPI:readConfiguration, status: 0
2019-04-07T20:45:00.103Z zigbee-shepherd:request REQ --> SAPI:readConfiguration
2019-04-07T20:45:00.117Z zigbee-shepherd:request RSP <-- SAPI:readConfiguration, status: 0
2019-04-07T20:45:00.129Z zigbee-shepherd:request REQ --> SAPI:readConfiguration
2019-04-07T20:45:00.161Z zigbee-shepherd:request RSP <-- SAPI:readConfiguration, status: 0
2019-04-07T20:45:00.173Z zigbee-shepherd:request REQ --> SAPI:readConfiguration
2019-04-07T20:45:00.190Z zigbee-shepherd:request RSP <-- SAPI:readConfiguration, status: 0
2019-04-07T20:45:00.204Z zigbee-shepherd:request REQ --> SAPI:getDeviceInfo
2019-04-07T20:45:00.218Z zigbee-shepherd:request RSP <-- SAPI:getDeviceInfo
2019-04-07T20:45:00.220Z zigbee-shepherd:init Now the ZNP is a coordinator.
2019-04-07T20:45:00.221Z zigbee-shepherd:request REQ --> SYS:version
2019-04-07T20:45:00.240Z zigbee-shepherd:request RSP <-- SYS:version
2019-04-07T20:45:00.244Z zigbee-shepherd:request REQ --> SAPI:getDeviceInfo
2019-04-07T20:45:00.256Z zigbee-shepherd:request RSP <-- SAPI:getDeviceInfo
2019-04-07T20:45:00.258Z zigbee-shepherd:request REQ --> SAPI:getDeviceInfo
2019-04-07T20:45:00.270Z zigbee-shepherd:request RSP <-- SAPI:getDeviceInfo
2019-04-07T20:45:00.272Z zigbee-shepherd:request REQ --> SAPI:getDeviceInfo
2019-04-07T20:45:00.284Z zigbee-shepherd:request RSP <-- SAPI:getDeviceInfo
2019-04-07T20:45:00.286Z zigbee-shepherd:request REQ --> SAPI:getDeviceInfo
2019-04-07T20:45:00.296Z zigbee-shepherd:request RSP <-- SAPI:getDeviceInfo
2019-04-07T20:45:00.297Z zigbee-shepherd:request REQ --> SAPI:getDeviceInfo
2019-04-07T20:45:00.307Z zigbee-shepherd:request RSP <-- SAPI:getDeviceInfo
2019-04-07T20:45:00.309Z zigbee-shepherd:request REQ --> SAPI:getDeviceInfo
2019-04-07T20:45:00.320Z zigbee-shepherd:request RSP <-- SAPI:getDeviceInfo
2019-04-07T20:45:00.325Z zigbee-shepherd:request REQ --> ZDO:nodeDescReq
2019-04-07T20:45:00.351Z zigbee-shepherd:msgHdlr IND <-- ZDO:nodeDescRsp
2019-04-07T20:45:00.356Z zigbee-shepherd:request REQ --> ZDO:activeEpReq
2019-04-07T20:45:00.376Z zigbee-shepherd:msgHdlr IND <-- ZDO:activeEpRsp
2019-04-07T20:45:00.409Z zigbee-shepherd:request REQ --> ZDO:simpleDescReq
2019-04-07T20:45:00.458Z zigbee-shepherd:msgHdlr IND <-- ZDO:simpleDescRsp
2019-04-07T20:45:00.460Z zigbee-shepherd:request REQ --> ZDO:simpleDescReq
2019-04-07T20:45:00.492Z zigbee-shepherd:msgHdlr IND <-- ZDO:simpleDescRsp
2019-04-07T20:45:00.493Z zigbee-shepherd:request REQ --> ZDO:simpleDescReq
2019-04-07T20:45:00.538Z zigbee-shepherd:msgHdlr IND <-- ZDO:simpleDescRsp
2019-04-07T20:45:00.539Z zigbee-shepherd:request REQ --> ZDO:simpleDescReq
2019-04-07T20:45:00.560Z zigbee-shepherd:msgHdlr IND <-- ZDO:simpleDescRsp
2019-04-07T20:45:00.562Z zigbee-shepherd:request REQ --> ZDO:simpleDescReq
2019-04-07T20:45:00.583Z zigbee-shepherd:msgHdlr IND <-- ZDO:simpleDescRsp
2019-04-07T20:45:00.584Z zigbee-shepherd:request REQ --> ZDO:simpleDescReq
2019-04-07T20:45:00.605Z zigbee-shepherd:msgHdlr IND <-- ZDO:simpleDescRsp
2019-04-07T20:45:00.613Z zigbee-shepherd:request REQ --> ZDO:nodeDescReq
2019-04-07T20:45:00.634Z zigbee-shepherd:msgHdlr IND <-- ZDO:nodeDescRsp
2019-04-07T20:45:00.635Z zigbee-shepherd:request REQ --> ZDO:activeEpReq
2019-04-07T20:45:00.655Z zigbee-shepherd:msgHdlr IND <-- ZDO:activeEpRsp
2019-04-07T20:45:00.661Z zigbee-shepherd:request REQ --> ZDO:mgmtPermitJoinReq
2019-04-07T20:45:00.684Z zigbee-shepherd:msgHdlr IND <-- ZDO:mgmtPermitJoinRsp
2019-04-07T20:45:00.764Z zigbee-shepherd:init Loading devices from database done.
2019-04-07T20:45:00.766Z zigbee-shepherd zigbee-shepherd is _ready and _enabled
  zigbee2mqtt:info 4/7/2019, 10:45:00 PM zigbee-shepherd started
  zigbee2mqtt:info 4/7/2019, 10:45:00 PM Coordinator firmware version: '20190223'
  zigbee2mqtt:debug 4/7/2019, 10:45:00 PM zigbee-shepherd info: {"enabled":true,"net":{"state":"Coordinator","channel":11,"panId":"0x1a62","extPanId":"0xdddddddddddddddd","ieeeAddr":"0x00124b00193663ef","nwkAddr":0},"firmware":{"transportrev":2,"product":0,"version":"2.6.3","revision":20190223},"startTime":1554669900,"joinTimeLeft":0}
  zigbee2mqtt:info 4/7/2019, 10:45:00 PM Currently 0 devices are joined:
  zigbee2mqtt:info 4/7/2019, 10:45:00 PM Zigbee: disabling joining new devices.
  zigbee2mqtt:info 4/7/2019, 10:45:00 PM Connecting to MQTT server at mqtt://192.168.86.110:8123
2019-04-07T20:45:00.976Z zigbee-shepherd:request REQ --> ZDO:mgmtPermitJoinReq
2019-04-07T20:45:00.990Z zigbee-shepherd:request REQ --> UTIL:ledControl
  zigbee2mqtt:info 4/7/2019, 10:45:00 PM zigbee-shepherd ready
2019-04-07T20:45:00.996Z zigbee-shepherd:request REQ --> AF:register
events.js:167
      throw er; // Unhandled 'error' event
      ^
Error: Not supported
    at Parser._parsePayload (/zigbee2mqtt-1.2.1/node_modules/mqtt-packet/parser.js:130:25)
    at Parser.parse (/zigbee2mqtt-1.2.1/node_modules/mqtt-packet/parser.js:37:48)
    at Writable.writable._write (/zigbee2mqtt-1.2.1/node_modules/mqtt/lib/client.js:301:12)
    at doWrite (/zigbee2mqtt-1.2.1/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/zigbee2mqtt-1.2.1/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/zigbee2mqtt-1.2.1/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:666:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
Emitted 'error' event at:
    at Parser.emit (events.js:182:13)
    at Parser._emitError (/zigbee2mqtt-1.2.1/node_modules/mqtt-packet/parser.js:372:8)
    at Parser._parsePayload (/zigbee2mqtt-1.2.1/node_modules/mqtt-packet/parser.js:130:14)
    at Parser.parse (/zigbee2mqtt-1.2.1/node_modules/mqtt-packet/parser.js:37:48)
    [... lines matching original stack trace ...]
    at Socket.emit (events.js:182:13)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.2.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.2.1 start script.
npm
 ERR! This is probably not a problem with npm. There is likely additional logging output above
```

I'm using Mosquitto 4.1 as MQTT broker and I'm running Home Assistant 0.91.0 on a Raspberry Pi.
This is my first try to get the plugin running.
Here is my config:
```
{
  "data_path": "/share/zigbee2mqtt",
  "homeassistant": true,
  "permit_join": false,
  "mqtt_base_topic": "zigbee2mqtt",
  "mqtt_server": "mqtt://homeassistant:1883",
  "serial_port": "/dev/ttyACM0",
  "devices": [],
  "network_key": [],
  "mqtt_user": "xxx",
  "mqtt_pass": "xxx",
  "log_level": "debug",
  "zigbee_shepherd_debug": true
}
```
Any thoughts what might be the problem?

**Comment by Piteriuz** [comment]
I have same problem. Help us :(

https://github.com/danielwelch/hassio-zigbee2mqtt/issues/173
https://community.home-assistant.io/t/some-errors-with-configure-first-smart-thing-with-zigbee2mqtt/120712

**Comment by danielwelch** [comment]
Have you posted in the zigbee2mqtt issue tracker? Looks like the add-on starts ok.
