### ISSUE TITLE
Zigbee2mqtt-edge slug name problem

### ISSUE THREAD

**Issue by matisaul** [danielwelch/hassio-zigbee2mqtt#153]
Hi,

I have a problem restarting the addon from hassio.addon_restart service. I think is because the minus sign in the name:

``` 
invalid slug 7ad98f9c_zigbee2mqtt-edge (try 7ad98f9c_zigbee2mqtt_edge) for dictionary value @ data['addon']
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 121, in handle_call_service
    connection.context(msg))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1118, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 267, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 589, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 427, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: invalid slug 7ad98f9c_zigbee2mqtt-edge (try 7ad98f9c_zigbee2mqtt_edge) for dictionary value @ data['addon']
```

I tried with `7ad98f9c_zigbee2mqtt_edge` but it doesn't work. Is there any chance to rename the slug to **7ad98f9c_zigbee2mqtt_edge** ?

Thanks in advance

**Comment by danielwelch** [comment]
Could you post the service call, JSON-formatted, as you’re using it?

**Comment by matisaul** [comment]
Service: **hassio.addon_restart**
Data:

```
{
  "addon": "7ad98f9c_zigbee2mqtt-edge"
}
```

**Comment by danielwelch** [comment]
I addressed this in the above issue. Planning to merge those changes in version 1.5.0.

**Comment by matisaul** [comment]
Thanks Daniel!
