### ISSUE TITLE
zigbee-shepherd:init Coordinator initialize had an error: Error: request timeout  

### ISSUE THREAD

**Issue by poldim** [danielwelch/hassio-zigbee2mqtt#164]
Experiencing a similar issue to #118 except mine says `zigbee-shepherd:init Coordinator initialize had an error: Error: request timeout` with different line number references.

- Latest HASSio + HA build
- Just updated to latest [CC2531_20190425](https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_Home_1.2/bin/CC2531_20190425.zip) firmware for the CC2531
- Tried using stable addon and edge addon versions
- Pressing the button does not bring it up

**Config:**
```
{
  "data_path": "/share/zigbee2mqtt",
  "homeassistant": true,
  "permit_join": false,
  "mqtt_base_topic": "zigbee2mqtt",
  "mqtt_server": "mqtt://homeassistant",
  "serial_port": "/dev/ttyAMA0",
  "devices": [],
  "network_key": [],
  "zigbee_shepherd_debug": true
}
```

**Log:**
```
[Info] Configuration file found: /share/zigbee2mqtt/configuration.yaml
[Info] Configuration written to /share/zigbee2mqtt/configuration.yaml
2019-05-21T09:58:57: PM2 log: Launching in no daemon mode
2019-05-21T09:58:58: PM2 log: App [npm:0] starting in -fork mode-
2019-05-21T09:58:58: PM2 log: App [npm:0] online
> zigbee2mqtt@1.4.0 start /app
> node index.js
  zigbee2mqtt:info 5/21/2019, 9:59:05 AM Logging to directory: '/share/zigbee2mqtt/log/2019-05-21.09-59-05'
  zigbee2mqtt:debug 5/21/2019, 9:59:05 AM Removing old log directory '/share/zigbee2mqtt/log/2019-05-21.09-44-35'
  zigbee2mqtt:debug 5/21/2019, 9:59:07 AM Using zigbee-shepherd with settings: '{"net":{"panId":6754,"extPanId":[221,221,221,221,221,221,221,221],"channelList":[11],"precfgkey":"HIDDEN"},"dbPath":"/share/zigbee2mqtt/database.db","coordBackupPath":"/share/zigbee2mqtt/coordinator_backup.json","sp":{"baudRate":115200,"rtscts":true}}'
  zigbee2mqtt:debug 5/21/2019, 9:59:07 AM Loaded state from file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 5/21/2019, 9:59:07 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:info 5/21/2019, 9:59:07 AM Starting zigbee2mqtt version 1.4.0 (commit #unknown)
  zigbee2mqtt:info 5/21/2019, 9:59:07 AM Starting zigbee-shepherd
2019-05-21T16:59:07.894Z zigbee-shepherd:init zigbee-shepherd booting...
2019-05-21T16:59:09.018Z zigbee-shepherd:request REQ --> SYS:version
2019-05-21T16:59:12.060Z zigbee-shepherd:request RSP <-- SYS:version
2019-05-21T16:59:12.085Z zigbee-shepherd:request REQ --> SYS:osalNvRead
2019-05-21T16:59:15.101Z zigbee-shepherd:request RSP <-- SYS:osalNvRead
2019-05-21T16:59:15.108Z zigbee-shepherd:init Coordinator initialize had an error: Error: request timeout
    at CcZnp.<anonymous> (/app/node_modules/cc-znp/lib/ccznp.js:269:22)
    at Object.onceWrapper (events.js:273:13)
    at CcZnp.emit (events.js:182:13)
    at Timeout.<anonymous> (/app/node_modules/cc-znp/lib/ccznp.js:248:18)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  zigbee2mqtt:info 5/21/2019, 9:59:15 AM Error while starting zigbee-shepherd, attempting to fix... (takes 60 seconds) (Error: request timeout)
  zigbee2mqtt:info 5/21/2019, 10:00:15 AM Starting zigbee-shepherd
2019-05-21T17:00:15.173Z zigbee-shepherd:init zigbee-shepherd booting...
2019-05-21T17:00:16.196Z zigbee-shepherd:request REQ --> SYS:version
2019-05-21T17:00:19.201Z zigbee-shepherd:request RSP <-- SYS:version
2019-05-21T17:00:19.205Z zigbee-shepherd:request REQ --> SYS:osalNvRead
2019-05-21T17:00:22.212Z zigbee-shepherd:request RSP <-- SYS:osalNvRead
2019-05-21T17:00:22.216Z zigbee-shepherd:init Coordinator initialize had an error: Error: request timeout
    at CcZnp.<anonymous> (/app/node_modules/cc-znp/lib/ccznp.js:269:22)
    at Object.onceWrapper (events.js:273:13)
    at CcZnp.emit (events.js:182:13)
    at Timeout.<anonymous> (/app/node_modules/cc-znp/lib/ccznp.js:248:18)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  zigbee2mqtt:error 5/21/2019, 10:00:22 AM Error while starting zigbee-shepherd! (Error: request timeout)
  zigbee2mqtt:error 5/21/2019, 10:00:22 AM Press the reset button on the stick (the one closest to the USB) and start again
  zigbee2mqtt:error 5/21/2019, 10:00:22 AM Failed to start
	{"message":"request timeout","stack":"Error: request timeout\n    at CcZnp.<anonymous> (/app/node_modules/cc-znp/lib/ccznp.js:269:22)\n    at Object.onceWrapper (events.js:273:13)\n    at CcZnp.emit (events.js:182:13)\n    at Timeout.<anonymous> (/app/node_modules/cc-znp/lib/ccznp.js:248:18)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)"}
  zigbee2mqtt:error 5/21/2019, 10:00:22 AM Exiting...
npm
 ERR! code ELIFECYCLE
npm ERR! errno
 1
npm ERR! zigbee2mqtt@1.4.0 start: `node index.js`
npm ERR! Exit status 1
npm 
ERR! 
npm ERR! Failed at the zigbee2mqtt@1.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-21T17_00_22_361Z-debug.log
2019-05-21T10:00:25: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2019-05-21T10:00:25: PM2 log: App [npm:0] starting in -fork mode-
2019-05-21T10:00:25: PM2 log: App [npm:0] online
> zigbee2mqtt@1.4.0 start /app
> node index.js
```

**Comment by poldim** [comment]
For reference: 
![image](https://user-images.githubusercontent.com/16869713/58116327-dc2e6780-7bb0-11e9-8fee-caa7332aa1b6.png)

**Comment by noob4722019** [comment]
I'm having the same issues. I've uninstalled the stable zigbee2mqtt addon and installed edge, no difference.

I'm using the latest firmware. Reset button seems to do nothing. 

I thought my my device died but I'm seeing this occur more frequently on the forums.

I'm gonna to try reflash tonight.
