### ISSUE TITLE
zigbee2mqtt addon stopped working after 0.94.2 HA update

### ISSUE THREAD

**Issue by vdwkes** [danielwelch/hassio-zigbee2mqtt#174]
Have run the 0.94.2 HA update and zigbee2mqtt give errors on restart
I run hassio on a RPi 3
log

`at handleErrorFromBinding (fs.js:113:24)
    at Object.statSync (fs.js:851:3)
    at fs.readdirSync.map (/zigbee2mqtt-1.4.0/lib/util/logger.js:50:36)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/zigbee2mqtt-1.4.0/lib/util/logger.js:48:53)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.4.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm
 ERR!     /root/.npm/_logs/2019-06-12T15_50_39_885Z-debug.log
2019-06-12T17:50:42: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2019-06-12T17:50:42: PM2 log: App [npm:0] starting in -fork mode-
2019-06-12T17:50:42: PM2 log: App [npm:0] online
> zigbee2mqtt@1.4.0 start /zigbee2mqtt-1.4.0
> node index.js
  zigbee2mqtt:info 6/12/2019, 5:50:45 PM Logging to directory: '/share/zigbee2mqtt/log/2019-06-12.17-50-45'
internal/errors.js:251
  const [ code, uvmsg ] = errmap.get(ctx.errno);
                                 ^
TypeError: errmap.get is not a function or its return value is not iterable
    at Object.uvException (internal/errors.js:251:34)
    at handleErrorFromBinding (fs.js:113:24)
    at Object.statSync (fs.js:851:3)
    at fs.readdirSync.map (/zigbee2mqtt-1.4.0/lib/util/logger.js:50:36)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/zigbee2mqtt-1.4.0/lib/util/logger.js:48:53)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.4.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm
 ERR!
 Failed at the zigbee2mqtt@1.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR!
 A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-12T15_50_45_799Z-debug.log
2019-06-12T17:50:47: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2019-06-12T17:50:47: PM2 log: App [npm:0] starting in -fork mode-
2019-06-12T17:50:47: PM2 log: App [npm:0] online
> zigbee2mqtt@1.4.0 start /zigbee2mqtt-1.4.0
> node index.js
  zigbee2mqtt:info 6/12/2019, 5:50:51 PM Logging to directory: '/share/zigbee2mqtt/log/2019-06-12.17-50-51'
internal/errors.js:251
  const [ code, uvmsg ] = errmap.get(ctx.errno);
                                 ^
TypeError: errmap.get is not a function or its return value is not iterable
    at Object.uvException (internal/errors.js:251:34)
    at handleErrorFromBinding (fs.js:113:24)
    at Object.statSync (fs.js:851:3)
    at fs.readdirSync.map (/zigbee2mqtt-1.4.0/lib/util/logger.js:50:36)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/zigbee2mqtt-1.4.0/lib/util/logger.js:48:53)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
npm
 
ERR!
 
code
 ELIFECYCLE
npm
 ERR! 
errno
 1
npm
 ERR! zigbee2mqtt@1.4.0 start: `node index.js`
npm ERR!
 Exit status 1
npm 
ERR! 
npm 
ERR! Failed at the zigbee2mqtt@1.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR!
 A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-12T15_50_51_668Z-debug.log
2019-06-12T17:50:53: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2019-06-12T17:50:53: PM2 log: App [npm:0] starting in -fork mode-
2019-06-12T17:50:53: PM2 log: App [npm:0] online`

**Comment by vdwkes** [comment]
sorry about the format of the log, i cant get it right

**Comment by vdwkes** [comment]
PM Logging to directory: '/share/zigbee2mqtt/log/2019-06-12.17-50-45'

These are all empty maps , no logs in them

**Comment by vdwkes** [comment]
tried to uninstall and re-install but didnt help. eventualy restored a snapshot to 0.94.1 and everything works again

**Comment by ema987** [comment]
Hello,

I updated from 0.93 to 0.94.4 with no issues at all :)

**Comment by vdwkes** [comment]
Thanks for the response. I will give it another try with 0.94.4

**Comment by vdwkes** [comment]
problem solved, updated to 0.95 and no problems. Dont know what the problem was.
