### ISSUE TITLE
1.5.1. logging error

### ISSUE THREAD

**Issue by EmmanuelLM** [danielwelch/hassio-zigbee2mqtt#187]
**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**
Dietpi on Odroid XU4 running Hassio
Hassio with Homeassistant 0.96.2
Zigbee2mqtt on Hassio 1.5.1

**Description of problem:**

zigbee2mqtt:info 7/21/2019, 8:38:40 AM Starting zigbee-shepherd
events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: ENOENT: no such file or directory, open '/share/zigbee2mqtt/log/2019-07-21.08-38-40/log.txt'
Emitted 'error' event at:
    at WriteStream.<anonymous> (/zigbee2mqtt-1.5.1/node_modules/winston/lib/winston/transports/file.js:491:16)
    at WriteStream.emit (events.js:198:13)
    at lazyFs.open (internal/fs/streams.js:277:12)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.5.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR!
 Failed at the zigbee2mqtt@1.5.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Your entire configuration from the frontend (with sensitive fields redacted)**
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "[]",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://homeassistant",
    "user": "my_user",
    "password": "my_password"
  },
  "serial": {
    "port": "/dev/ttyACM0"
  },
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      8,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ]
  }
}

**Comment by furiaceka87** [comment]
I have same, error.. with same configuration...

**Comment by EmmanuelLM** [comment]
It looks to me it cannot open the log file for writing, which would point to a permission issue but given nothing on my side has changed between 1.4.1 and 1.5.1, I am thinking it is something with the Hassio implementation?

**Comment by CTLS** [comment]
I seem to have the same issue.

**Comment by mclaudiopt** [comment]
i also have same problem
```
./run.sh: line 15: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
2019-07-21T20:04:36: PM2 log: Launching in no daemon mode
2019-07-21T20:04:36: PM2 log: App [npm:0] starting in -fork mode-
2019-07-21T20:04:36: PM2 log: App [npm:0] online
> zigbee2mqtt@1.5.1 start /zigbee2mqtt-1.5.1
> node index.js
  zigbee2mqtt:info 7/21/2019, 8:04:37 PM Logging to directory: '/share/zigbee2mqtt/log/2019-07-21.20-04-37'
  zigbee2mqtt:info 7/21/2019, 8:04:37 PM Starting zigbee2mqtt version 1.5.1 (commit #unknown)
  zigbee2mqtt:info 7/21/2019, 8:04:37 PM Starting zigbee-shepherd
/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/dist/lib/components/controller.js:429
                    throw new TypeError('net.precfgkey should be an array with 16 uint8 integers.');
                    ^
TypeError: net.precfgkey should be an array with 16 uint8 integers.
    at /zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/dist/lib/components/controller.js:429:27
    at Object._.forOwn (/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/node_modules/busyman/index.js:242:27)
    at Object._.forEach (/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/node_modules/busyman/index.js:415:18)
    at Controller.setNvParams (/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/dist/lib/components/controller.js:414:7)
    at new ZShepherd (/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/dist/lib/shepherd.js:28:21)
    at Zigbee.start (/zigbee2mqtt-1.5.1/lib/zigbee.js:57:25)
    at startupLogVersion (/zigbee2mqtt-1.5.1/lib/controller.js:167:25)
    at utils.getZigbee2mqttVersion (/zigbee2mqtt-1.5.1/lib/controller.js:193:13)
    at git.getLastCommit (/zigbee2mqtt-1.5.1/lib/util/utils.js:102:9)
    at /zigbee2mqtt-1.5.1/node_modules/git-last-commit/source/index.js:44:5
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.5.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
 
npm ERR! Failed at the zigbee2mqtt@1.5.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-21T19_04_37_672Z-debug.log
2019-07-21T20:04:41: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2019-07-21T20:04:41: PM2 log: App [npm:0] starting in -fork mode-
2019-07-21T20:04:41: PM2 log: App [npm:0] online
> zigbee2mqtt@1.5.1 start /zigbee2mqtt-1.5.1
> node index.js
  zigbee2mqtt:info 7/21/2019, 8:04:42 PM Logging to directory: '/share/zigbee2mqtt/log/2019-07-21.20-04-42'
  zigbee2mqtt:info 7/21/2019, 8:04:42 PM Starting zigbee2mqtt version 1.5.1 (commit #unknown)
  zigbee2mqtt:info 7/21/2019, 8:04:42 PM Starting zigbee-shepherd
/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/dist/lib/components/controller.js:429
                    throw new TypeError('net.precfgkey should be an array with 16 uint8 integers.');
                    ^
TypeError: net.precfgkey should be an array with 16 uint8 integers.
    at /zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/dist/lib/components/controller.js:429:27
    at Object._.forOwn (/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/node_modules/busyman/index.js:242:27)
    at Object._.forEach (/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/node_modules/busyman/index.js:415:18)
    at Controller.setNvParams (/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/dist/lib/components/controller.js:414:7)
    at new ZShepherd (/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/dist/lib/shepherd.js:28:21)
    at Zigbee.start (/zigbee2mqtt-1.5.1/lib/zigbee.js:57:25)
    at startupLogVersion (/zigbee2mqtt-1.5.1/lib/controller.js:167:25)
    at utils.getZigbee2mqttVersion (/zigbee2mqtt-1.5.1/lib/controller.js:193:13)
    at git.getLastCommit (/zigbee2mqtt-1.5.1/lib/util/utils.js:102:9)
    at /zigbee2mqtt-1.5.1/node_modules/git-last-commit/source/index.js:44:5
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.5.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
 
npm ERR! Failed at the zigbee2mqtt@1.5.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by EmmanuelLM** [comment]
You error seems to be different, you are missing a network key (see other thread about this).
Network key is now compulsory under 1.5.1

**Comment by EmmanuelLM** [comment]
@danielwelch could this be similar to this? [https://github.com/danielwelch/hassio-zigbee2mqtt/issues/54](url)

**Comment by furiaceka87** [comment]
I solved this issue by fill mqtt with the mqtt://ipaddress:port
Username and password, before I had my_user and my_password.

**Comment by EmmanuelLM** [comment]
And no issues with creating the logs?

**Comment by danielwelch** [comment]
@EmmanuelLM have you tried defining the log directory explicitly in the config? I'm assuming you didn't specify it before, and still are not specifying it now.

**Comment by CTLS** [comment]
@danielwelch @EmmanuelLM adding  "log_directory": "data/log/%TIMESTAMP%", under advanced fixes the issue.

**Comment by EmmanuelLM** [comment]
Works perfectly, thank you!
