### ISSUE TITLE
Can't install the addon

### ISSUE THREAD

**Issue by nokiandrea** [danielwelch/hassio-zigbee2mqtt#234]
My Home Assistant versione: 0.98.1

This is my error log:
```
19-09-29 10:09:31 INFO (SyncWorker_8) [hassio.docker.interface] Pull image dwelch2101/zigbee2mqtt-armhf tag 1.6.0.
19-09-29 10:09:33 ERROR (SyncWorker_8) [hassio.docker.interface] Can't install dwelch2101/zigbee2mqtt-armhf:1.6.0 -> 500 Server Error: Internal Server Error ("readlink /mnt/data/docker/overlay2/l: invalid argument").
```

**Comment by ciotlosm** [comment]
Are you using HassOS or some generic docker installation? Looks like remote server (which in this case would be docker hub) replied with 500. 

Maybe do a retry and see if it works

**Comment by Clem-** [comment]
I have a similar issue: 
`ERROR (SyncWorker_14) [hassio.docker.interface] Can't install dwelch2101/zigbee2mqtt-armhf:1.6.0 -> 500 Server Error: Internal Server Error ("Get https://registry-1.docker.io/v2/dwelch2101/zigbee2mqtt-armhf/manifests/1.6.0: Get https://auth.docker.io/token?scope=repository%3Adwelch2101%2Fzigbee2mqtt-armhf%3Apull&service=registry.docker.io: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)").`

**Comment by bmtKIA6** [comment]
same here. Can not upgrade from 1.5* to 1.6.

`19-10-27 23:58:21 INFO (SyncWorker_3) [hassio.docker.interface] Update image dwelch2101/zigbee2mqtt-armhf:1.6.0 to dwelch2101/zigbee2mqtt-armhf:1.6.0
19-10-27 23:58:21 INFO (SyncWorker_3) [hassio.docker.interface] Pull image dwelch2101/zigbee2mqtt-armhf tag 1.6.0.
19-10-27 23:58:21 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.39/images/sha256:6a0cca52aeaeaf381a15838b41df29ec0cf9c87b786668542be211474d7e6d5b/json
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/hassio/hassio/api/security.py", line 147, in token_validation
    return await handler(request)
  File "/usr/src/hassio/hassio/api/utils.py", line 39, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/hassio/hassio/addons/__init__.py", line 205, in update
    await addon.instance.cleanup()
  File "/usr/src/hassio/hassio/utils/__init__.py", line 29, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/hassio/hassio/docker/interface.py", line 320, in _cleanup
    for image in self.sys_docker.images.list(name=self.image):
  File "/usr/local/lib/python3.7/site-packages/docker/models/images.py", line 364, in list
    return [self.get(r["Id"]) for r in resp]
  File "/usr/local/lib/python3.7/site-packages/docker/models/images.py", line 364, in <listcomp>
    return [self.get(r["Id"]) for r in resp]
  File "/usr/local/lib/python3.7/site-packages/docker/models/images.py", line 316, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/image.py", line 246, in inspect_image
    self._get(self._url("/images/{0}/json", image)), True
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("readlink /mnt/data/docker/overlay2/l: invalid argument")
19-10-27 23:58:41 INFO (SyncWorker_10) [hassio.docker.addon] Start Docker add-on dwelch2101/zigbee2mqtt-armhf with version 1.5.1.1`

HassOS 2.12
hass.io supervisor: 192

**Comment by ciotlosm** [comment]
You could try uninstall / reinstall of the addon, as most of the settings are persisted in `/share/zigbee2mqtt`

**Comment by Reisga** [comment]
I had same error earlier, in homeassistant forum they recommended to check if there disk is full,
 in console run command:
 **df -h** 
if the disk is not full, then you might have  some corrupted files, to fix them run command:
 **hassio su repair**

that fixed my error.

**Comment by danielwelch** [comment]
Yeah, these errors are usually because of disk space or some other issue with the docker host.

**Comment by bmtKIA6** [comment]
As pointed out by @Reisga `hassio su repair` solved the issue

**Comment by JasperDelbaere** [comment]
I cant confirm "hassio su repair" works
