### ISSUE TITLE
Not able to update from 1.5.1.2 to 1.6.0

### ISSUE THREAD

**Issue by proton999** [danielwelch/hassio-zigbee2mqtt#235]
I'm not able to update de zigbee2mqtt addon from 1.5.1.2 to 1.6.0. I'm using HASSIO on a rpi 3b+
with HA version 99.3. I tried to update when I was on HA version 97.2 but I didn't succeed so I'll updated HA to 99.3 but still not possible to update.

I'll moved de cc2531 stick to a different usb poort, i'll removed the home-assistant.db, i'll rebooted 
but without luck. Can you give me some suggestions were to look ?

Below my z2m addon config: (Which is working fine with 1.5.1.2 )
```
{
    "data_path": "/share/zigbee2mqtt",
    "devices": "devices.yaml",
    "groups": "groups.yaml",
    "homeassistant": true,
    "permit_join": false,
    "mqtt": {
        "base_topic": "zigbee2mqtt",
        "server": "mqtt://homeassistant:1883",
        "user": "admin",
        "password": "xxxxxxx"
    },
    "serial": {
        "port": "/dev/ttyACM0",
        "disable_led": true
    },
    "advanced": {
        "pan_id": 6754,
        "channel": 11,
        "network_key": [
            1,
            3,
            5,
            7,
            9,
            11,
            13,
            15,
            0,
            2,
            4,
            6,
            8,
            10,
            12,
            13
        ],
        "availability_blacklist": []
    },
    "ban": [],
    "whitelist": [],
    "queue": {},
    "zigbee_shepherd_devices": true
```

Below is the Z2M Log after I it's updated to 1.6.0.

```
Log
npm ERR! A complete log of this run can be found in:
npm 
ERR!     /root/.npm/_logs/2019-09-29T15_14_51_880Z-debug.log
2019-09-29T17:14:52: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2019-09-29T17:14:52: PM2 log: App [npm:0] starting in -fork mode-
2019-09-29T17:14:52: PM2 log: App [npm:0] online
> zigbee2mqtt@1.6.0 start /zigbee2mqtt-1.6.0
> node index.js
/zigbee2mqtt-1.6.0/lib/util/utils.js:44
        .map((mappedModel) => mappedModel.zigbeeModel));
                                          ^
TypeError: Cannot read property 'zigbeeModel' of undefined
    at flatten.map.map (/zigbee2mqtt-1.6.0/lib/util/utils.js:44:43)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/zigbee2mqtt-1.6.0/lib/util/utils.js:44:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.6.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm
 ERR!     /root/.npm/_logs/2019-09-29T15_14_58_080Z-debug.log
2019-09-29T17:14:58: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2019-09-29T17:14:58: PM2 log: App [npm:0] starting in -fork mode-
2019-09-29T17:14:58: PM2 log: App [npm:0] online
> zigbee2mqtt@1.6.0 start /zigbee2mqtt-1.6.0
> node index.js
/zigbee2mqtt-1.6.0/lib/util/utils.js:44
        .map((mappedModel) => mappedModel.zigbeeModel));
                                          ^
TypeError: Cannot read property 'zigbeeModel' of undefined
    at flatten.map.map (/zigbee2mqtt-1.6.0/lib/util/utils.js:44:43)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/zigbee2mqtt-1.6.0/lib/util/utils.js:44:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 
ERR! zigbee2mqtt@1.6.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!
     /root/.npm/_logs/2019-09-29T15_15_04_044Z-debug.log
2019-09-29T17:15:04: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2019-09-29T17:15:04: PM2 log: App [npm:0] starting in -fork mode-
2019-09-29T17:15:04: PM2 log: App [npm:0] online
> zigbee2mqtt@1.6.0 start /zigbee2mqtt-1.6.0
> node index.js
/zigbee2mqtt-1.6.0/lib/util/utils.js:44
        .map((mappedModel) => mappedModel.zigbeeModel));
                                          ^
TypeError: Cannot read property 'zigbeeModel' of undefined
    at flatten.map.map (/zigbee2mqtt-1.6.0/lib/util/utils.js:44:43)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/zigbee2mqtt-1.6.0/lib/util/utils.js:44:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.6.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!
     /root/.npm/_logs/2019-09-29T15_15_09_637Z-debug.log
2019-09-29T17:15:10: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2019-09-29T17:15:10: PM2 log: App [npm:0] starting in -fork mode-
2019-09-29T17:15:10: PM2 log: App [npm:0] online
```

**Comment by filoor** [comment]
Hi,

I had the same issue.
I have removed "database.db" and now its working.

**Comment by proton999** [comment]
Just remove the database.db ? Do I have to re-pair every device again ?

**Comment by alfem** [comment]
I also got that error. I removed _node_modules_ subdirectory and recreate it with _npm install_. Then, I restarted my Pi and everything is running fine now.

**Comment by proton999** [comment]
@alfem   I'm a total noob on linux so can you tell me how to recreate the node_modules folder with the npm install command within hassio ?

**Comment by alfem** [comment]
I am afraid I am not using hassio but a local custom installation of zigbee2mqtt and home-assistant. Try to find the folder where zigbee2mqtt is installed, and you will find the _node_modules_ subdirectory under it.

**Comment by baldfox** [comment]
Hi there, did anyone manage to get this fixed? I just updated my hassio and also upgraded zigbee2mqtt add on from 1.5.1 to 1.6.0 and now I can't seem to get any log at all out of it. It doesn't even attempt to start.  

19-10-14 12:25:37 ERROR (MainThread) [hassio.addons.addon] Add-on 7ad98f9c_zigbee2mqtt have wrong options: Missing option availability_blacklist in advanced. Got {'data_path': '/share/zigbee2mqtt', 'devices': 'decices.yaml', 'groups': 'groups.yaml', 'homeassistant': True, 'permit_join': False, 'mqtt': {'base_topic': 'zigbee2mqtt', 'server': 'mqtt://homeassistant', 'user': 'XX', 'password': 'XXXXXXXXXXXXX'}, 'serial': {'port': '/dev/ttyACM0'}, 'advanced': {'pan_id': 6754, 'channel': 11, 'network_key': [1, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 10, 12, 13]}, 'ban': [], 'whitelist': [], 'queue': {}}

This was all I managed to get. To be clear I managed to get past the 1.5.1 upgrade issue and all was working normally.

**Comment by ciotlosm** [comment]
@baldfox You have a problem in your config for the addon. See:

```
wrong options: Missing option availability_blacklist in advanced
```

**Comment by baldfox** [comment]
> @baldfox You have a problem in your config for the addon. See:
> 
> ```
> wrong options: Missing option availability_blacklist in advanced
> ```

Can you expand a little? I never had any issues before, and didn't see anything about needing to add the above availability_blacklist in the read me files? thx

**Comment by ciotlosm** [comment]
@baldfox it's probably a change in the configuration that adds this parameter as required, even if empty. Look at the config from the original poster, you need in your `advanced` section the line with `"availability_blacklist": []`

@proton999 Did you fix your installation? Things to try: reinstall the addon, backup data in `/share/zigbee2mqtt` somewhere else and start the addon without that.

**Comment by proton999** [comment]
@ciotlosm I hadn't fixed it yet and I was about to try youre suggestion but I had added "zigbee_shepherd_devices": true to the config to control a new light bulb a few z2m versions ago.
This was working fine.  So I'll thought before reinstalling the addon again I remove the "zigbee_shepherd_devices": true line from the config. After removing that line the update from 1.5.1.2 to 1.6.0 went fine. For me this issue can be closed. Thanks !

**Comment by ciotlosm** [comment]
Thanks for sharing.

**Comment by markheloking** [comment]
It seems the required config options have changed between updates, but the upgrade doesn't automatically upgrade the config.

I had to remove:

```
advanced:
  "availability_blacklist": []
'ban': [],
'whitelist': [],
```

And then insert:
```
advanced:
  availability_blocklist: []
  availability_passlist: []
```

**Comment by ciotlosm** [comment]
This is a known issue as documented here: https://github.com/danielwelch/hassio-zigbee2mqtt/issues/384
