### ISSUE TITLE
Not starting after Hassio v1.0

### ISSUE THREAD

**Issue by ciB89** [danielwelch/hassio-zigbee2mqtt#238]
**zigbee2mqtt add-on version (if edge, please report commit hash):**

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**
zigbee2mqtt version 1.6.0 (commit #3e75108741a0d7328b278a8c26daaf8a5adf0934)

**Description of problem:**
Updated Hassio to latest version, now zigbee2mqtt/herdsman does not work anymore. Using the edge-version on the lates commit. (https://github.com/Koenkk/zigbee-herdsman/issues/63)

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://#######:1883",
    "user": "####",
    "password": "#####"
  },
  "serial": {
    "port": "/dev/ttyACM0",
    "disable_led": false
  },
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blacklist": [],
    "log_level": "debug",
    "report": true
  },
  "ban": [],
  "whitelist": [],
  "queue": {}
}
```

**Your logs from Hass.io**

```
zigbee2mqtt:error 2019-10-11T14:18:52: Error while starting zigbee-herdsman
zigbee2mqtt:error 2019-10-11T14:18:52: Error: SRSP - SYS - version after 6000ms
    at Timeout.object.timer.setTimeout [as _onTimeout] (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
zigbee2mqtt:error 2019-10-11T14:18:52: Failed to start zigbee
zigbee2mqtt:error 2019-10-11T14:18:52: Exiting...
zigbee2mqtt:error 2019-10-11T14:18:52: Error: SRSP - SYS - version after 6000ms
    at Timeout.object.timer.setTimeout [as _onTimeout] (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by ciB89** [comment]
Just realized its an issue with lates dev version, not hassio itself. Downgrading to an older dev-version fixed it for me
