### ISSUE TITLE
Fresh install with version 1.6.0 does not start

### ISSUE THREAD

**Issue by tortfeaser** [danielwelch/hassio-zigbee2mqtt#240]
This was a running install, had to reinstall HassOS for another problem. Starting from scratch, now I get this error.

**zigbee2mqtt add-on version (if edge, please report commit hash): 1.6.0, 1.6.0 edge, same problem.

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io): 

RPi 3B+ running HassOS 0.100.2

**Description of problem:**

I can't start Zigbee2MQTT. I get the following error:
```
./run.sh: line 16: [Info] Configuration backup found in /config/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
2019-10-17T18:04:03: PM2 log: Launching in no daemon mode
2019-10-17T18:04:04: PM2 log: App [npm:0] starting in -fork mode-
2019-10-17T18:04:04: PM2 log: App [npm:0] online
> zigbee2mqtt@1.6.0 start /zigbee2mqtt-1.6.0
> node index.js
  zigbee2mqtt:info 10/17/2019, 6:04:10 PM Logging to directory: '/config/zigbee2mqtt/log/2019-10-17.18-04-08'
  zigbee2mqtt:debug 10/17/2019, 6:04:10 PM Removing old log directory '/config/zigbee2mqtt/log/2019-10-17.17-56-21'
  zigbee2mqtt:debug 10/17/2019, 6:04:10 PM Removing old log directory '/config/zigbee2mqtt/log/2019-10-17.17-56-15'
  zigbee2mqtt:debug 10/17/2019, 6:04:10 PM Can't load state from file /config/zigbee2mqtt/state.json (doesn't exist)
  zigbee2mqtt:debug 10/17/2019, 6:04:10 PM Saving state to file /config/zigbee2mqtt/state.json
  zigbee2mqtt:info 10/17/2019, 6:04:10 PM Starting zigbee2mqtt version 1.6.0 (commit #unknown)
  zigbee2mqtt:info 10/17/2019, 6:04:10 PM Starting zigbee-shepherd
  zigbee2mqtt:debug 10/17/2019, 6:04:10 PM Using zigbee-shepherd with settings: '{"net":{"panId":6754,"extPanId":[221,221,221,221,221,221,221,221],"channelList":[11],"precfgkey":"HIDDEN"},"dbPath":"/config/zigbee2mqtt/database.db","coordBackupPath":"/config/zigbee2mqtt/coordinator_backup.json","sp":{"baudRate":115200,"rtscts":true}}'
  zigbee2mqtt:info 10/17/2019, 6:04:24 PM Error while starting zigbee-shepherd, attempting to fix... (takes 60 seconds) (Error: SRSP - SYS - osalNvRead after 6000ms)
  zigbee2mqtt:info 10/17/2019, 6:05:24 PM Starting zigbee-shepherd
  zigbee2mqtt:error 10/17/2019, 6:05:37 PM Error while starting zigbee-shepherd! (Error: SRSP - SYS - osalNvRead after 6000ms)
  zigbee2mqtt:error 10/17/2019, 6:05:37 PM Press the reset button on the stick (the one closest to the USB) and start again
  zigbee2mqtt:error 10/17/2019, 6:05:37 PM Failed to start
	{"message":"SRSP - SYS - osalNvRead after 6000ms","stack":"Error: SRSP - SYS - osalNvRead after 6000ms\n    at Timeout.object.timer.setTimeout [as _onTimeout] (/zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/dist/znp/znp.js:227:24)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)"}
  zigbee2mqtt:error 10/17/2019, 6:05:37 PM Exiting...
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.6.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.6.0 start script.
npm ERR!
 This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-17T07_05_37_118Z-debug.log
2019-10-17T18:05:40: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
```

**Your entire configuration from the frontend (with sensitive fields redacted)**

```
{
  "data_path": "/config/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://192.168.1.200",
    "user": "mqtt",
    "password": "*****"
  },
  "serial": {
    "port": "/dev/ttyAMA0"
  },
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blacklist": [],
    "log_level": "debug",
    "report": "true"
  },
  "ban": [],
  "whitelist": [],
  "queue": {},
  "include_device_information": "true"
}
```

**Your logs from Hass.io**

As above

**Comment by JarnoNijboer** [comment]
Reflashing stick with latest firmware should fix this. This problem seems to occur after upgrading from 1.5.x to 1.6

**Comment by tortfeaser** [comment]
Gave that a shot. Wasn't the problem. But once I removed the line ```  "include_device_information": "true"``` it started fine.

**Comment by ciotlosm** [comment]
@tortfeaser Can this issue be closed?

**Comment by tortfeaser** [comment]
Aye. Yes thanks.
