### ISSUE TITLE
can’t work with ti cc1352p-2 test case

### ISSUE THREAD

**Issue by flower87lucky** [danielwelch/hassio-zigbee2mqtt#241]
Zigbee2mqtt-edge
I used cc1352p-2

```
pi@raspberrypi:~ $ ls -l /dev/serial/by-id
total 0
lrwxrwxrwx 1 root root 13 Oct 19 23:29 usb-Texas_Instruments_XDS110__02.03.00.18__Embed_with_CMSIS-DAP_L43000GM-if00 -> ../../ttyACM0
lrwxrwxrwx 1 root root 13 Oct 19 23:29 usb-Texas_Instruments_XDS110__02.03.00.18__Embed_with_CMSIS-DAP_L43000GM-if03 -> ../../ttyACM1
pi@raspberrypi:~ $
```

I don’t know ,it works with erro.
```
./run.sh: line 16: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
[Info] Socat is DISABLED and not started
2019-10-20T07:56:51: PM2 log: Launching in no daemon mode
2019-10-20T07:56:51: PM2 log: App [npm:0] starting in -fork mode-
2019-10-20T07:56:51: PM2 log: App [npm:0] online
```

```
zigbee2mqtt@1.6.0 start /app
node index.js
zigbee2mqtt:info 2019-10-19T23:56:54: Logging to directory: '/share/zigbee2mqtt/log/2019-10-20.07-56-54'
zigbee2mqtt:info 2019-10-19T23:56:54: Starting zigbee2mqtt version 1.6.0 (commit #0f9046134f98a10c50bf404e9ca0664747bb97d7)
zigbee2mqtt:info 2019-10-19T23:56:54: Starting zigbee-herdsman...
zigbee2mqtt:error 2019-10-19T23:57:02: Error while starting zigbee-herdsman
zigbee2mqtt:error 2019-10-19T23:57:02: Failed to start zigbee
zigbee2mqtt:error 2019-10-19T23:57:02: Exiting...
zigbee2mqtt:error 2019-10-19T23:57:02: Error: SRSP - SYS - version after 6000ms
at Timeout.object.timer.setTimeout [as _onTimeout] (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
at ontimeout (timers.js:436:11)
at tryOnTimeout (timers.js:300:5)
at listOnTimeout (timers.js:263:5)
at Timer.processTimers (timers.js:223:10)
npm
ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.6.0 start: node index.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2019-10-19T23_57_02_174Z-debug.log
2019-10-20T07:57:02: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2019-10-20T07:57:02: PM2 log: App [npm:0] starting in -fork mode-
2019-10-20T07:57:02: PM2 log: App
```

**Comment by flower87lucky** [comment]
works good with cc2531,not work with cc1352p-2

**Comment by fredrikgk** [comment]
As mentioned here: #Koenkk/zigbee2mqtt/issues/2162 , you are using a deprecated version of the CC1352P LaunchPad. That is why it is not working.

**Comment by Koenkk** [comment]
@fredrikgk thanks, I will close this.
