### ISSUE TITLE
Exception in async_discover_sensor when dispatching 'mqtt_discovery_new_sensor_mqtt'

### ISSUE THREAD

**Issue by vpomax** [danielwelch/hassio-zigbee2mqtt#245]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
zigbee2mqtt v. 1.6

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**
Hassio 0.100.3

**Description of problem:**
Exception in async_discover_sensor when dispatching 'mqtt_discovery_new_sensor_mqtt'

**Your entire configuration from the frontend (with sensitive fields redacted)**:

```
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": true,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://192.168.1.X:1883",
    "user": "xxxxxxxx",
    "password": "xxxxxxxx"
  },
  "serial": {
    "port": "/dev/ttyACM0"
  },
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blacklist": []
  },
  "ban": [],
  "whitelist": [],
  "queue": {}
}

```

**Your logs from Hass.io**
```
2019-10-25 14:36:34 ERROR (MainThread) [homeassistant.components.mqtt.sensor] Exception in async_discover_sensor when dispatching 'mqtt_discovery_new_sensor_mqtt': ({'device_class': 'battery', 'name': 'Presenza Corridoio Battery', 'state_topic': 'homeassistant/sensor/motion_sensor_158d00016dafd8_battery/state', 'unit_of_measurement': '%', 'unique_id': 'motion_sensor_158d00016dafd8_battery', 'source_entity_id': 'binary_sensor.motion_sensor_158d00016dafd8', 'source_attribute': 'battery_level', 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 81, in async_discover_sensor
    config = PLATFORM_SCHEMA(discovery_payload)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['source_entity_id']

2019-10-25 14:36:34 ERROR (MainThread) [homeassistant.components.mqtt.sensor] Exception in async_discover_sensor when dispatching 'mqtt_discovery_new_sensor_mqtt': ({'device_class': 'battery', 'name': 'Illumination_158d0002234653 Battery', 'state_topic': 'homeassistant/sensor/illumination_158d0002234653_battery/state', 'unit_of_measurement': '%', 'unique_id': 'illumination_158d0002234653_battery', 'source_entity_id': 'sensor.illumination_158d0002234653', 'source_attribute': 'battery_level', 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 81, in async_discover_sensor
    config = PLATFORM_SCHEMA(discovery_payload)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['source_entity_id']

2019-10-25 14:36:34 ERROR (MainThread) [homeassistant.components.mqtt.sensor] Exception in async_discover_sensor when dispatching 'mqtt_discovery_new_sensor_mqtt': ({'device_class': 'battery', 'name': 'Sensore presenza Studio Battery', 'state_topic': 'homeassistant/sensor/motion_sensor_158d0002234653_battery/state', 'unit_of_measurement': '%', 'unique_id': 'motion_sensor_158d0002234653_battery', 'source_entity_id': 'binary_sensor.motion_sensor_158d0002234653', 'source_attribute': 'battery_level', 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 81, in async_discover_sensor
    config = PLATFORM_SCHEMA(discovery_payload)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['source_entity_id']

2019-10-25 14:36:34 ERROR (MainThread) [homeassistant.components.mqtt.sensor] Exception in async_discover_sensor when dispatching 'mqtt_discovery_new_sensor_mqtt': ({'device_class': 'battery', 'name': 'Temperatura Terrazza Battery', 'state_topic': 'homeassistant/sensor/temperature_158d0001d36c92_battery/state', 'unit_of_measurement': '%', 'unique_id': 'temperature_158d0001d36c92_battery', 'source_entity_id': 'sensor.temperature_158d0001d36c92', 'source_attribute': 'battery_level', 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 81, in async_discover_sensor
    config = PLATFORM_SCHEMA(discovery_payload)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['source_entity_id']
```

...........
.......
....

**Comment by vpomax** [comment]
Problem solved myself unistalling and reinstalling Mosquitto app-on for Hassio.
