### ISSUE TITLE
Upgrade to 1.7.1 fails to start

### ISSUE THREAD

**Issue by daenny** [danielwelch/hassio-zigbee2mqtt#265]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.7.1

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**
VM with ubuntu 18.04 server with hassio

**Description of problem:**
Upgrade to 1.7.1 fails. The container does not start correctly. See output below.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://xxxx",
    "user": "xxx",
    "password": "xxx"
  },
  "serial": {
    "port": "/dev/ttyUSB0"
  },
  "advanced": {
    "log_level": "info",
    "pan_id": xxxx,
    "channel": 11,
    "rtscts": false,
    "network_key": [
xxxx
    ],
    "availability_blacklist": []
  },
  "ban": [],
  "whitelist": [],
  "queue": {}
}
```

**Your logs from Hass.io**

```
zigbee2mqtt:info  2019-11-22T01:16:45: Logging to directory: '/share/zigbee2mqtt/log/2019-11-22.02-16-45'
zigbee2mqtt:info  2019-11-22T01:16:45: Starting zigbee2mqtt version 1.7.1 (commit #unknown)
zigbee2mqtt:info  2019-11-22T01:16:45: Starting zigbee-herdsman...
zigbee2mqtt:error 2019-11-22T01:16:47: Error while starting zigbee-herdsman
zigbee2mqtt:error 2019-11-22T01:16:47: Failed to start zigbee
zigbee2mqtt:error 2019-11-22T01:16:47: Exiting...
zigbee2mqtt:error 2019-11-22T01:16:47: Error: Device with ieeeAddr '0x00124b00xxxxx' already exists
    at Function.create (/zigbee2mqtt-1.7.1/node_modules/zigbee-herdsman/dist/controller/model/device.js:159:19)
    at Controller.<anonymous> (/zigbee2mqtt-1.7.1/node_modules/zigbee-herdsman/dist/controller/controller.js:117:32)
    at Generator.next (<anonymous>)
    at fulfilled (/zigbee2mqtt-1.7.1/node_modules/zigbee-herdsman/dist/controller/controller.js:5:58)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.7.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.7.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by daenny** [comment]
Ok, I resolved this by manually removing all entries regarding the `0x00124b00xxxxx` address from the database. Now it seems to work again.
