### ISSUE TITLE
Unable to pair new devices

### ISSUE THREAD

**Issue by gitechlo** [danielwelch/hassio-zigbee2mqtt#27]
I get the message in log shortly after startup - 

```
2018-6-11 10:18:45 INFO
{"message":"request unsuccess: 16","stack":"Error: request unsuccess: 16
 at /app/node_modules/zigbee-shepherd/lib/components/zdo.js:46:21
 at CcZnp. (/app/node_modules/cc-znp/lib/ccznp.js:257:13)
 at Object.onceWrapper (events.js:315:30)
 at emitOne (events.js:116:13)
 at CcZnp.emit (events.js:211:7)
 at CcZnp._mtIncomingDataHdlr (/app/node_modules/cc-znp/lib/ccznp.js:357:14)
 at /app/node_modules/cc-znp/lib/ccznp.js:333:22
 at _combinedTickCallback (internal/process/next_tick.js:131:7)
 at process._tickCallback (internal/process/next_tick.js:180:9)"}
```

Existing devices in DB & config communicate fine.

**Comment by ciotlosm** [comment]
@gitechlo Could you try another reinstall of the addon? There was a bug with a dependency during the weekend. 

For others, reposting the error message formatter:
```
2018-6-11 10:18:45 INFO
{"message":"request unsuccess: 16","stack":"Error: request unsuccess: 16
 at /app/node_modules/zigbee-shepherd/lib/components/zdo.js:46:21
 at CcZnp. (/app/node_modules/cc-znp/lib/ccznp.js:257:13)
 at Object.onceWrapper (events.js:315:30)
 at emitOne (events.js:116:13)
 at CcZnp.emit (events.js:211:7)
 at CcZnp._mtIncomingDataHdlr (/app/node_modules/cc-znp/lib/ccznp.js:357:14)
 at /app/node_modules/cc-znp/lib/ccznp.js:333:22
 at _combinedTickCallback (internal/process/next_tick.js:131:7)
 at process._tickCallback (internal/process/next_tick.js:180:9)"}
```
@danielwelch maybe permit rights to edit issues in the future? Would be nice if I could help with tagging and cleaning up things.

**Comment by gitechlo** [comment]
Thanks ciotlosm reinstalled and devices now pair, although I'm not sure if my Zigbee router is now connected? I'm getting this output in log - 

2018-06-12T06:10:52.170Z - error:  TypeError: Cannot read property 'zclClustersReq' of null
    at /app/node_modules/zigbee-shepherd/lib/components/event_handlers.js:195:32
    at _fulfilled (/app/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/app/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/app/node_modules/q/q.js:816:13)
    at /app/node_modules/q/q.js:877:14
    at runSingle (/app/node_modules/q/q.js:137:13)
    at flush (/app/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
2018-06-12T06:10:52.469Z - info: zigbee-shepherd started
2018-06-12T06:10:52.480Z - info: Currently 1 devices are joined:
2018-06-12T06:10:52.483Z - info: unknown (0x00124b0012013a17): unkown - undefined unknown (Router)

I'm presuming routers don't show up in the device list? Some devices show in log as routers, presuming these end devices are actually linked via router?

2018-06-12T07:11:38.426Z - info: Xiaomi Temp 3 (0x00158d00023748ca): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
2018-06-12T07:11:38.431Z - info: Xiaomi PIR 2 (0x00158d0001f9d124): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
2018-06-12T07:11:38.433Z - info: Xiaomi Temp 2 (0x00158d0002374d9f): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
2018-06-12T07:11:38.435Z - info: Xiaomi PIR 3 (0x00158d0001dc0195): RTCGQ01LM - Xiaomi MiJia human body movement sensor (EndDevice)
2018-06-12T07:11:38.440Z - info: Door Light (0x000b57fffee796a8): LED1623G12 - IKEA TRADFRI LED bulb E27 1000 lumen, dimmable, opal white (Router)
info: Xiaomi Temp 1 (0x00158d00023764fc): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
info: Xiaomi PIR 1 (0x00158d000200ebb9): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
info: lamp 1 (0x90fd9ffffe8ea1a8): LED1536G5 - IKEA TRADFRI LED bulb E12/E14 400 lumen, dimmable, white spectrum, opal white **(Router)**
info: lamp 2 (0x90fd9ffffe887d7d): LED1536G5 - IKEA TRADFRI LED bulb E12/E14 400 lumen, dimmable, white spectrum, opal white **(Router)**

**Comment by ciotlosm** [comment]
@gitechlo I think this is a problem with [zigbee2mqtt](https://github.com/Koenkk/zigbee2mqtt) itself. I'll close this issue here. On the [other repository](https://github.com/Koenkk/zigbee2mqtt) there are already a couple of issues similar to yours. Might be worth checking those out.
