### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by unpack8866** [danielwelch/hassio-zigbee2mqtt#314]
**zigbee2mqtt add-on version (if edge, please report commit hash):**

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**

**Description of problem:**

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
// replace this line with your pasted configuration
```

**Your logs from Hass.io**

> zigbee2mqtt@1.11.0 start /zigbee2mqtt-1.11.0
> node index.js
zigbee2mqtt:info  2020-03-23 11:49:42: Logging to console and directory: '/share/zigbee2mqtt/log/2020-03-23.11-49-42' filename: log.txt
zigbee2mqtt:info  2020-03-23 11:49:42: Starting zigbee2mqtt version 1.11.0 (commit #unknown)
zigbee2mqtt:info  2020-03-23 11:49:42: Starting zigbee-herdsman...
zigbee2mqtt:error 2020-03-23 11:50:29: Error while starting zigbee-herdsman
zigbee2mqtt:error 2020-03-23 11:50:29: Failed to start zigbee
zigbee2mqtt:error 2020-03-23 11:50:29: Exiting...
zigbee2mqtt:error 2020-03-23 11:50:29: Error: SRSP - SYS - osalNvWrite after 6000ms
    at Timeout._onTimeout (/zigbee2mqtt-1.11.0/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.11.0 start: `node index.js`
npm ERR!
 Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.11.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-23T03_50_29_804Z-debug.log
2020-03-23T11:50:32: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2020-03-23T11:50:32: PM2 log: App [npm:0] starting in -fork mode-
2020-03-23T11:50:32: PM2 log: App [npm:0] online
> zigbee2mqtt@1.11.0 start /zigbee2mqtt-1.11.0
> node index.js
zigbee2mqtt:info  2020-03-23 11:50:33: Logging to console and directory: '/share/zigbee2mqtt/log/2020-03-23.11-50-33' filename: log.txt
zigbee2mqtt:info  2020-03-23 11:50:33: Starting zigbee2mqtt version 1.11.0 (commit #unknown)
zigbee2mqtt:info  2020-03-23 11:50:33: Starting zigbee-herdsman...
(node:287) UnhandledPromiseRejectionWarning: Error: SRSP - ZDO - activeEpReq after 6000ms
    at Timeout._onTimeout (/zigbee2mqtt-1.11.0/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:287) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:287) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by unpack8866** [comment]
9d6","type":"Router","networkAddress":28701,"model":"QBKG03LM","friendly_name":"0x00158d00012f79d6","manufacturerID":4151,"manufacturerName":"LUMI","modelID":"lumi.ctrl_neutral2","lastSeen":1584941730187}]}'


(node:263) UnhandledPromiseRejectionWarning: Error: AREQ - AF - dataConfirm after 3000ms


    at Timeout._onTimeout (/zigbee2mqtt-1.11.0/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)


    at listOnTimeout (internal/timers.js:531:17)


    at processTimers (internal/timers.js:475:7)


(node:263) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)


(node:263) UnhandledPromiseRejectionWarning: Error: AREQ - AF - dataConfirm after 3000ms


    at Timeout._onTimeout (/zigbee2mqtt-1.11.0/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)


    at listOnTimeout (internal/timers.js:531:17)


    at processTimers (internal/timers.js:475:7)


(node:263) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
