### ISSUE TITLE
Hive motion sensors MOT003 are now supported but no lux or temperature is being reported

### ISSUE THREAD

**Issue by dnedeltchev** [danielwelch/hassio-zigbee2mqtt#345]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
latest
**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**

Raspberry Pi 4, latest OS, latest add-ons, etc.

**Description of problem:**
MOT003 Hive motion sensors are supported according to the zigbee2mqtt supported devices page and indeed they do pair successfully and I can see all sensors but... the only sensor data that I can get is motion and battery. The temperature and lux sensors return no data at all.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
// replace this line with your pasted configuration
```

**Your logs from Hass.io**

Here is a copy of an error that I see sometimes for the temperature on one of the hive sensors. As far as I can see, there are no errors about the lux. Also during the pairing of a hive sensor this error does not come up. I cannot tell when it is shows up. The sensors do report temperature when paired directly with the hive hub. I have 3 hive sensors and they all behave this way, I thought this may be a bad sensor but ...

zigbee2mqtt:info  2020-06-08 18:15:31: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_announced","message":"announce","meta":{"friendly_name":"0x00124b001312b72c"}}'
zigbee2mqtt:error 2020-06-08 18:15:41: Failed to configure '0x00124b001312b72c', attempt 3 (Error: Bind 0x00124b001312b72c/6 msTemperatureMeasurement from '0x00124b0018e322e2/1' failed (Error: AREQ - ZDO - bindRsp after 10000ms)
    at Endpoint.<anonymous> (/zigbee2mqtt-1.13.1/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:244:23)
    at Generator.throw (<anonymous>)
    at rejected (/zigbee2mqtt-1.13.1/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65))

Thanks for all your help!

Let me know if you need any other info from my system.

D Nedeltchev

**Comment by dnedeltchev** [comment]
Correction on the data that is successfully received from the hive sensor... I get the following, it's not _just_ motion (occupancy) and battery.

occupancy
tamper
battery low
linkquality

**Comment by dnedeltchev** [comment]
not related, have raised an issue on Koenkk
