### ISSUE TITLE
Issue with 0.1.1

### ISSUE THREAD

**Issue by talondnb** [danielwelch/hassio-zigbee2mqtt#42]
I’m getting the following since upgrading:

/zigbee2mqtt-0.1.1/node_modules/zcl-packet/lib/foundation.js:683
        ru[dataType](name)(this);
                    ^
TypeError: ru[dataType] is not a function
    at Dissolve.<anonymous> (/zigbee2mqtt-0.1.1/node_modules/zcl-packet/lib/foundation.js:683:21)
    at Dissolve._transform (/zigbee2mqtt-0.1.1/node_modules/dissolve/index.js:80:16)
    at Dissolve.Transform._read (/zigbee2mqtt-0.1.1/node_modules/dissolve/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Dissolve.Transform._write (/zigbee2mqtt-0.1.1/node_modules/dissolve/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/zigbee2mqtt-0.1.1/node_modules/dissolve/node_modules/readable-stream/lib/_stream_writable.js:279:12)
    at writeOrBuffer (/zigbee2mqtt-0.1.1/node_modules/dissolve/node_modules/readable-stream/lib/_stream_writable.js:266:5)
    at Dissolve.Writable.write (/zigbee2mqtt-0.1.1/node_modules/dissolve/node_modules/readable-stream/lib/_stream_writable.js:211:11)
    at Dissolve.Writable.end (/zigbee2mqtt-0.1.1/node_modules/dissolve/node_modules/readable-stream/lib/_stream_writable.js:426:10)
    at FoundPayload._getObj (/zigbee2mqtt-0.1.1/node_modules/zigbee-shepherd/node_modules/zcl-packet/lib/foundation.js:242:12)
    at getObjCB (/zigbee2mqtt-0.1.1/node_modules/zigbee-shepherd/node_modules/zcl-packet/lib/foundation.js:51:22)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@0.1.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@0.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by shokwaav** [comment]
I'm getting this issue too.

**Comment by jasimancas** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/236

**Comment by mdroberts1243** [comment]
What I see after upgrading:
[Info] Configuration file found. Will overwrite configurable               fields with values from add-on configuration
[Info] Configuration written to /share/zigbee2mqtt/configuration.yaml
[2018-07-31T10:37:49.485Z] PM2 log: Launching in no daemon mode
[2018-07-31T10:37:49.905Z] PM2 log: Starting execution sequence in -fork mode- for app name:npm id:0
[2018-07-31T10:37:49.944Z] PM2 log: App name:npm id:0 online
> zigbee2mqtt@0.1.1 start /zigbee2mqtt-0.1.1
> node index.js
2018-7-31 10:37:54 INFO Starting zigbee2mqtt version 0.1.1 (commit #unknown)
2018-7-31 10:37:54 INFO Starting zigbee-shepherd
2018-7-31 10:37:58 INFO zigbee-shepherd started
2018-7-31 10:37:58 INFO Currently 6 devices are joined:
2018-7-31 10:37:58 INFO unknown (0x00158d000234825f): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
2018-7-31 10:37:58 INFO unknown (0x00158d000200e064): unkown - undefined unknown (EndDevice)
2018-7-31 10:37:58 INFO 0x00158d00020479d5 (0x00158d00020479d5): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
2018-7-31 10:37:58 INFO 0x00158d00023cf4c5 (0x00158d00023cf4c5): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
2018-7-31 10:37:58 INFO 0x00158d00023cf654 (0x00158d00023cf654): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
2018-7-31 10:37:58 INFO 0x00158d000236b618 (0x00158d000236b618): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
2018-7-31 10:37:58 INFO Connecting to MQTT server at mqtt://homeassistant
2018-7-31 10:37:59 INFO zigbee-shepherd ready
2018-7-31 10:37:59 INFO Connected to MQTT server
2018-7-31 10:37:59 INFO MQTT publish, topic: 'zigbee2mqtt/bridge/state', payload: 'online'
2018-7-31 10:37:59 INFO MQTT publish, topic: 'homeassistant/binary_sensor/0x00158d00020479d5/occupancy/config', payload: '{"payload_on":true,"payload_off":false,"value_template":"{{ value_json.occupancy }}","device_class":"motion","json_attributes":["battery","voltage"],"state_topic":"zigbee2mqtt/0x00158d00020479d5","availability_topic":"zigbee2mqtt/bridge/state","name":"0x00158d00020479d5_occupancy","unique_id":"0x00158d00020479d5_occupancy_zigbee2mqtt"}'
2018-7-31 10:37:59 INFO MQTT publish, topic: 'homeassistant/sensor/0x00158d00020479d5/illuminance/config', payload: '{"unit_of_measurement":"lx","icon":"mdi:theme-light-dark","value_template":"{{ value_json.illuminance }}","json_attributes":["battery","voltage"],"state_topic":"zigbee2mqtt/0x00158d00020479d5","availability_topic":"zigbee2mqtt/bridge/state","name":"0x00158d00020479d5_illuminance","unique_id":"0x00158d00020479d5_illuminance_zigbee2mqtt"}'
2018-7-31 10:37:59 INFO MQTT publish, topic: 'homeassistant/sensor/0x00158d00023cf4c5/temperature/config', payload: '{"unit_of_measurement":"°C","icon":"mdi:temperature-celsius","value_template":"{{ value_json.temperature }}","json_attributes":["battery","voltage"],"state_topic":"zigbee2mqtt/0x00158d00023cf4c5","availability_topic":"zigbee2mqtt/bridge/state","name":"0x00158d00023cf4c5_temperature","unique_id":"0x00158d00023cf4c5_temperature_zigbee2mqtt"}'
2018-7-31 10:37:59 INFO MQTT publish, topic: 'homeassistant/sensor/0x00158d00023cf4c5/humidity/config', payload: '{"unit_of_measurement":"%","icon":"mdi:water-percent","value_template":"{{ value_json.humidity }}","json_attributes":["battery","voltage"],"state_topic":"zigbee2mqtt/0x00158d00023cf4c5","availability_topic":"zigbee2mqtt/bridge/state","name":"0x00158d00023cf4c5_humidity","unique_id":"0x00158d00023cf4c5_humidity_zigbee2mqtt"}'
2018-7-31 10:37:59 INFO MQTT publish, topic: 'homeassistant/sensor/0x00158d00023cf4c5/pressure/config', payload: '{"unit_of_measurement":"Pa","icon":"mdi:speedometer","value_template":"{{ value_json.pressure }}","json_attributes":["battery","voltage"],"state_topic":"zigbee2mqtt/0x00158d00023cf4c5","availability_topic":"zigbee2mqtt/bridge/state","name":"0x00158d00023cf4c5_pressure","unique_id":"0x00158d00023cf4c5_pressure_zigbee2mqtt"}'
2018-7-31 10:37:59 INFO MQTT publish, topic: 'homeassistant/sensor/0x00158d00023cf654/temperature/config', payload: '{"unit_of_measurement":"°C","icon":"mdi:temperature-celsius","value_template":"{{ value_json.temperature }}","json_attributes":["battery","voltage"],"state_topic":"zigbee2mqtt/0x00158d00023cf654","availability_topic":"zigbee2mqtt/bridge/state","name":"0x00158d00023cf654_temperature","unique_id":"0x00158d00023cf654_temperature_zigbee2mqtt"}'
2018-7-31 10:37:59 INFO MQTT publish, topic: 'homeassistant/sensor/0x00158d00023cf654/humidity/config', payload: '{"unit_of_measurement":"%","icon":"mdi:water-percent","value_template":"{{ value_json.humidity }}","json_attributes":["battery","voltage"],"state_topic":"zigbee2mqtt/0x00158d00023cf654","availability_topic":"zigbee2mqtt/bridge/state","name":"0x00158d00023cf654_humidity","unique_id":"0x00158d00023cf654_humidity_zigbee2mqtt"}'
2018-7-31 10:37:59 INFO MQTT publish, topic: 'homeassistant/sensor/0x00158d00023cf654/pressure/config', payload: '{"unit_of_measurement":"Pa","icon":"mdi:speedometer","value_template":"{{ value_json.pressure }}","json_attributes":["battery","voltage"],"state_topic":"zigbee2mqtt/0x00158d00023cf654","availability_topic":"zigbee2mqtt/bridge/state","name":"0x00158d00023cf654_pressure","unique_id":"0x00158d00023cf654_pressure_zigbee2mqtt"}'
2018-7-31 10:37:59 INFO MQTT publish, topic: 'homeassistant/binary_sensor/0x00158d000236b618/occupancy/config', payload: '{"payload_on":true,"payload_off":false,"value_template":"{{ value_json.occupancy }}","device_class":"motion","json_attributes":["battery","voltage"],"state_topic":"zigbee2mqtt/0x00158d000236b618","availability_topic":"zigbee2mqtt/bridge/state","name":"0x00158d000236b618_occupancy","unique_id":"0x00158d000236b618_occupancy_zigbee2mqtt"}'
2018-7-31 10:37:59 INFO MQTT publish, topic: 'homeassistant/sensor/0x00158d000236b618/illuminance/config', payload: '{"unit_of_measurement":"lx","icon":"mdi:theme-light-dark","value_template":"{{ value_json.illuminance }}","json_attributes":["battery","voltage"],"state_topic":"zigbee2mqtt/0x00158d000236b618","availability_topic":"zigbee2mqtt/bridge/state","name":"0x00158d000236b618_illuminance","unique_id":"0x00158d000236b618_illuminance_zigbee2mqtt"}'
/zigbee2mqtt-0.1.1/node_modules/zcl-packet/lib/foundation.js:297
        dataTypeStr = zclId.dataType(dataType).key;
                                              ^
TypeError: Cannot read property 'key' of undefined
    at ensureDataTypeString (/zigbee2mqtt-0.1.1/node_modules/zcl-packet/lib/foundation.js:297:47)
    at getDataType (/zigbee2mqtt-0.1.1/node_modules/zcl-packet/lib/foundation.js:307:16)
    at Dissolve.<anonymous> (/zigbee2mqtt-0.1.1/node_modules/zcl-packet/lib/foundation.js:682:24)
    at Dissolve._transform (/zigbee2mqtt-0.1.1/node_modules/dissolve/index.js:80:16)
    at Dissolve.Transform._read (/zigbee2mqtt-0.1.1/node_modules/dissolve/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Dissolve.Transform._write (/zigbee2mqtt-0.1.1/node_modules/dissolve/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/zigbee2mqtt-0.1.1/node_modules/dissolve/node_modules/readable-stream/lib/_stream_writable.js:279:12)
    at writeOrBuffer (/zigbee2mqtt-0.1.1/node_modules/dissolve/node_modules/readable-stream/lib/_stream_writable.js:266:5)
    at Dissolve.Writable.write (/zigbee2mqtt-0.1.1/node_modules/dissolve/node_modules/readable-stream/lib/_stream_writable.js:211:11)
    at Dissolve.Writable.end (/zigbee2mqtt-0.1.1/node_modules/dissolve/node_modules/readable-stream/lib/_stream_writable.js:426:10)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@0.1.1 start: `node index.js`
npm ERR!
 Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@0.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!
     /root/.npm/_logs/2018-07-31T14_38_02_086Z-debug.log
[2018-07-31T10:38:02.733Z] PM2 log: App [npm] with id [0] and pid [24], exited with code [1] via signal [SIGINT]
[2018-07-31T10:38:02.745Z] PM2 log: Starting execution sequence in -fork mode- for app name:npm id:0
[2018-07-31T10:38:02.772Z] PM2 log: App name:npm id:0 online
> zigbee2mqtt@0.1.1 start /zigbee2mqtt-0.1.1
> node index.js
2018-7-31 10:38:07 INFO Starting zigbee2mqtt version 0.1.1 (commit #unknown)
2018-7-31 10:38:07 INFO Starting zigbee-shepherd

**Comment by Koenkk** [comment]
@danielwelch can you update zigbee2mqtt to 0.1.2? This should fix this issue.

**Comment by SirSheik** [comment]
Hello
I have the same problem.
How could I update to that version hass.io addon?
The only version avable in the repository is 0.1.1
Thanks for this brilliant addon.

**Comment by danielwelch** [comment]
I will do my best to update tonight!

**Comment by danielwelch** [comment]
see https://github.com/danielwelch/hassio-zigbee2mqtt/releases/tag/v0.1.2

**Comment by talondnb** [comment]
Confirmed no longer an issue. Thanks so much for the quick turnaround! Really appreciate the work.

**Comment by mdroberts1243** [comment]
Works for me too! Thanks!
