### ISSUE TITLE
Error while starting zigbee-herdsman

### ISSUE THREAD

**Issue by Limych** [danielwelch/hassio-zigbee2mqtt#426]
**zigbee2mqtt add-on version (if edge, please report commit hash):** 
1.14.4.2

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):** 

Hassio on Docker on Raspberry PI

**Description of problem:**

Add-on failed when trying to start. Repeatedly.

In this case, the adapter is correctly detected when trying to manually connect:
```shell
pi@raspberrypi:~$ ls -l /dev/serial/by-id
total 0
lrwxrwxrwx 1 root root 13 Oct  1 13:26 usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0014D95FD1-if00 -> ../../ttyACM0
```

On previous versions of the addon, everything worked fine with exactly the same settings. On what exact version the breakdown occurred, I cannot say for sure.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto:1883'
  user: '!secret mqtt_username'
  password: '!secret mqtt_password'
serial:
  port: /dev/ttyACM0
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key: []
  network_key_string: '!secret zigbee2mqt_network_key'
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```

**Your logs from Home Assistant**
```text
Zigbee2MQTT:info  2020-10-01 16:25:41: Starting Zigbee2MQTT version 1.14.4 (commit #1.14.4)
Zigbee2MQTT:info  2020-10-01 16:25:41: Starting zigbee-herdsman...
Zigbee2MQTT:error 2020-10-01 16:26:04: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2020-10-01 16:26:04: Failed to start zigbee
Zigbee2MQTT:error 2020-10-01 16:26:04: Exiting...
Zigbee2MQTT:error 2020-10-01 16:26:04: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/zigbee2mqtt-1.14.4/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:90:31)
    at Generator.throw (<anonymous>)
    at rejected (/zigbee2mqtt-1.14.4/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.14.4 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.14.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm
 ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-01T13_26_05_749Z-debug.log
2020-10-01T16:26:08: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2020-10-01T16:26:08: PM2 log: App [npm:0] starting in -fork mode-
2020-10-01T16:26:09: PM2 log: App [npm:0] online
> zigbee2mqtt@1.14.4 start /zigbee2mqtt-1.14.4
> node index.js
Zigbee2MQTT:info  2020-10-01 16:26:34: Logging to console and directory: '/share/zigbee2mqtt/log/2020-10-01.16-26-34' filename: log.txt
Zigbee2MQTT:info  2020-10-01 16:26:42: Starting Zigbee2MQTT version 1.14.4 (commit #1.14.4)
Zigbee2MQTT:info  2020-10-01 16:26:42: Starting zigbee-herdsman...
Zigbee2MQTT:error 2020-10-01 16:27:05: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2020-10-01 16:27:05: Failed to start zigbee
Zigbee2MQTT:error 2020-10-01 16:27:05: Exiting...
```

**Comment by ciotlosm** [comment]
This is usually a problem with your adapter. Read through https://github.com/Koenkk/zigbee2mqtt/issues/2997
Usually you can try pressing the reset button on the adapter, but if nothing fails you might need to re-flash the stick.

This is not a problem with z2m add-on, but with the actual communication between z2m and the adapter. Usually these issues should go here: https://github.com/Koenkk/zigbee2mqtt/issues

**Comment by Limych** [comment]
Thank you for support. Re-flashing of the stick fixed the problem.
