### ISSUE TITLE
Error while starting zigbee2MQTT

### ISSUE THREAD

**Issue by McPaHa** [danielwelch/hassio-zigbee2mqtt#449]
**zigbee2mqtt add-on version (if edge, please report commit hash):**

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**
HassOS 4.13

**Description of problem:**
This stopped working at last night without any changes. I flashed my CC2531 stick again without any help CC2531ZNP-with-SBL.hex

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```yaml
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.1.99:1883'
  user: mqtt
  password: mqtt
serial:
  port: /dev/ttyACM0
advanced:
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
  availability_timeout: 60
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```

**Your logs from Home Assistant**
```
> zigbee2mqtt@1.15.0 start /zigbee2mqtt-1.15.0
> node index.js
Zigbee2MQTT:info  2020-10-16 10:46:47: Logging to console and directory: '/share/zigbee2mqtt/log/2020-10-16.10-46-47' filename: log.txt
Zigbee2MQTT:info  2020-10-16 10:46:48: Starting Zigbee2MQTT version 1.15.0 (commit #1.15.0)
Zigbee2MQTT:info  2020-10-16 10:46:48: Starting zigbee-herdsman...
Zigbee2MQTT:error 2020-10-16 10:47:08: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2020-10-16 10:47:08: Failed to start zigbee
Zigbee2MQTT:error 2020-10-16 10:47:08: Exiting...
Zigbee2MQTT:error 2020-10-16 10:47:08: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/zigbee2mqtt-1.15.0/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:92:31)
    at Generator.throw (<anonymous>)
    at rejected (/zigbee2mqtt-1.15.0/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.15.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.15.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-16T07_47_08_294Z-debug.log
2020-10-16T10:47:08: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2020-10-16T10:47:08: PM2 log: App [npm:0] starting in -fork mode-
2020-10-16T10:47:08: PM2 log: App [npm:0] online
> zigbee2mqtt@1.15.0 start /zigbee2mqtt-1.15.0
> node index.js
Zigbee2MQTT:info  2020-10-16 10:47:11: Logging to console and directory: '/share/zigbee2mqtt/log/2020-10-16.10-47-11' filename: log.txt
Zigbee2MQTT:info  2020-10-16 10:47:12: Starting Zigbee2MQTT version 1.15.0 (commit #1.15.0)
Zigbee2MQTT:info  2020-10-16 10:47:12: Starting zigbee-herdsman...
Zigbee2MQTT:error 2020-10-16 10:47:32: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2020-10-16 10:47:32: Failed to start zigbee
Zigbee2MQTT:error 2020-10-16 10:47:32: Exiting...
Zigbee2MQTT:error 2020-10-16 10:47:32: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/zigbee2mqtt-1.15.0/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:92:31)
    at Generator.throw (<anonymous>)
    at rejected (/zigbee2mqtt-1.15.0/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm 
ERR! zigbee2mqtt@1.15.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.15.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-16T07_47_32_816Z-debug.log
2020-10-16T10:47:33: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2020-10-16T10:47:33: PM2 log: App [npm:0] starting in -fork mode-
2020-10-16T10:47:33: PM2 log: App [npm:0] online
> zigbee2mqtt@1.15.0 start /zigbee2mqtt-1.15.0
> node index.js
Zigbee2MQTT:info  2020-10-16 10:47:36: Logging to console and directory: '/share/zigbee2mqtt/log/2020-10-16.10-47-36' filename: log.txt
Zigbee2MQTT:info  2020-10-16 10:47:37: Starting Zigbee2MQTT version 1.15.0 (commit #1.15.0)
Zigbee2MQTT:info  2020-10-16 10:47:37: Starting zigbee-herdsman...
Zigbee2MQTT:info  2020-10-16 10:47:47: zigbee-herdsman started
Zigbee2MQTT:info  2020-10-16 10:47:47: Coordinator firmware version: '{"meta":{"maintrel":2,"majorrel":2,"minorrel":7,"product":2,"revision":20190425,"transportrev":2},"type":"zStack30x"}'
Zigbee2MQTT:info  2020-10-16 10:47:47: Currently 0 devices are joined:
Zigbee2MQTT:warn  2020-10-16 10:47:47: `permit_join` set to  `true` in configuration.yaml.
Zigbee2MQTT:warn  2020-10-16 10:47:47: Allowing new devices to join.
Zigbee2MQTT:warn  2020-10-16 10:47:47: Set `permit_join` to `false` once you joined all devices.
Zigbee2MQTT:info  2020-10-16 10:47:47: Zigbee: allowing new devices to join.
Zigbee2MQTT:info  2020-10-16 10:47:47: Started frontend on port 8099
Zigbee2MQTT:info  2020-10-16 10:47:47: Connecting to MQTT server at mqtt://192.168.1.99:1883
Zigbee2MQTT:info  2020-10-16 10:47:48: Connected to MQTT server
Zigbee2MQTT:info  2020-10-16 10:47:48: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
Zigbee2MQTT:info  2020-10-16 10:47:48: MQTT publish: topic 'zigbee2mqtt/bridge/info', payload '{"commit":"1.15.0","config":{"advanced":{"adapter_concurrent":null,"availability_blacklist":[],"availability_blocklist":[],"availability_passlist":[],"availability_timeout":60,"availability_whitelist":[],"cache_state":true,"cache_state_persistent":true,"cache_state_send_on_startup":true,"channel":11,"elapsed":false,"ext_pan_id":[221,221,221,221,221,221,221,221],"homeassistant_discovery_topic":"homeassistant","homeassistant_legacy_triggers":true,"homeassistant_status_topic":"hass/status","last_seen":"disable","legacy_api":true,"log_directory":"/share/zigbee2mqtt/log/%TIMESTAMP%","log_file":"log.txt","log_level":"info","log_output":["console","file"],"log_rotation":true,"log_syslog":{},"pan_id":6754,"report":false,"soft_reset_timeout":0,"timestamp_format":"YYYY-MM-DD HH:mm:ss"},"ban":[],"blocklist":[],"device_options":{},"devices":{"0x680ae2fffe97ad47":{"friendly_name":"0x680ae2fffe97ad47"},"0x680ae2fffea7e281":{"friendly_name":"0x680ae2fffea7e281"},"0x680ae2fffef91930":{"friendly_name":"0x680ae2fffef91930"},"0xec1bbdfffe2de77b":{"friendly_name":"0xec1bbdfffe2de77b"},"0xec1bbdfffe8811cb":{"friendly_name":"0xec1bbdfffe8811cb"},"0xec1bbdfffe8812d5":{"friendly_name":"0xec1bbdfffe8812d5"},"0xec1bbdfffe9ebc14":{"friendly_name":"0xec1bbdfffe9ebc14"}},"experimental":{"new_api":true,"output":"json"},"external_converters":[],"frontend":{"port":8099},"groups":{},"homeassistant":true,"map_options":{"graphviz":{"colors":{"fill":{"coordinator":"#e04e5d","enddevice":"#fff8ce","router":"#4ea3e0"},"font":{"coordinator":"#ffffff","enddevice":"#000000","router":"#ffffff"},"line":{"active":"#009900","inactive":"#994444"}}}},"mqtt":{"base_topic":"zigbee2mqtt","include_device_information":false,"password":"mqtt","server":"mqtt://192.168.1.99:1883","user":"mqtt"},"passlist":[],"permit_join":true,"queue":{},"serial":{"disable_led":false,"port":"/dev/ttyACM0"},"whitelist":[]},"coordinator":{"meta":{"maintrel":2,"majorrel":2,"minorrel":7,"product":2,"revision":20190425,"transportrev":2},"type":"zStack30x"},"log_level":"info","network":{"channel":11,"extended_pan_id":"0x00124b0014d47b96","pan_id":6755},"permit_join":true,"version":"1.15.0"}'
Zigbee2MQTT:info  2020-10-16 10:47:48: MQTT publish: topic 'zigbee2mqtt/bridge/devices', payload '[{"definition":null,"endpoints":{"1":{"bindings":[],"clusters":{"input":[],"output":[]}},"11":{"bindings":[],"clusters":{"input":["ssIasAce"],"output":["ssIasZone","ssIasWd"]}},"110":{"bindings":[],"clusters":{"input":[],"output":[]}},"12":{"bindings":[],"clusters":{"input":[],"output":[]}},"13":{"bindings":[],"clusters":{"input":["genOta"],"output":[]}},"2":{"bindings":[],"clusters":{"input":[],"output":[]}},"242":{"bindings":[],"clusters":{"input":[],"output":[]}},"3":{"bindings":[],"clusters":{"input":[],"output":[]}},"4":{"bindings":[],"clusters":{"input":[],"output":[]}},"47":{"bindings":[],"clusters":{"input":[],"output":[]}},"5":{"bindings":[],"clusters":{"input":[],"output":[]}},"6":{"bindings":[],"clusters":{"input":[],"output":[]}},"8":{"bindings":[],"clusters":{"input":[],"output":[]}}},"friendly_name":"Coordinator","ieee_address":"0x00124b0014d47b96","interview_completed":true,"interviewing":false,"network_address":0,"supported":false,"type":"Coordinator"}]'
Zigbee2MQTT:info  2020-10-16 10:47:48: MQTT publish: topic 'zigbee2mqtt/bridge/groups', payload '[]'
Zigbee2MQTT:info  2020-10-16 10:47:48: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"1.15.0","coordinator":{"meta":{"maintrel":2,"majorrel":2,"minorrel":7,"product":2,"revision":20190425,"transportrev":2},"type":"zStack30x"},"log_level":"info","network":{"channel":11,"extendedPanID":"0x00124b0014d47b96","panID":6755},"permit_join":true,"version":"1.15.0"}'
```

**Comment by ciotlosm** [comment]
It seems your add-on is working now. But the error: `Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)` is usually happening when z2m can't connect to the stick. 

This is not really a problem of the add-on but of the z2m (issues go here: https://github.com/Koenkk/zigbee2mqtt/issues/new/choose)

To solve this you usually have a few action courses (that you can try in order):
- Press reset button on stick
- Removing and reinserting the stick
- Re-flashing the stick firmware

**Comment by ciotlosm** [comment]
@McPaHa Can you confirm if your add-on is working now?

**Comment by McPaHa** [comment]
Oh sorry... It's working now

su 1. marrask. 2020 klo 12.27 Marius <notifications@github.com> kirjoitti:
