### ISSUE TITLE
Error: Failed to connect to the adapter

### ISSUE THREAD

**Issue by coom** [danielwelch/hassio-zigbee2mqtt#505]
**zigbee2mqtt add-on version:** 1.16.2.2 (stable)

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):** Home Assistant OS 5.9 installed though OVA.
Supervisor 2020.12.7 (stable)

**Description of problem:** 
Fresh install, the plugin cannot connect to the MQTT broker. Tried to install Zigbee2MQTT on a Debian with same configuration and everything works as expected. The problem seems to be related to the home assistant plugin only.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: mqtt
  password: my_super_secure_password
serial:
  port: /dev/ttyACM0
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 2
  initialdelay: 2
  options: '-d -d'

```

**Your logs from Home Assistant**

Zigbee2MQTT:error 2020-12-28 19:58:22: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2020-12-28 19:58:22: Failed to start zigbee
Zigbee2MQTT:error 2020-12-28 19:58:22: Exiting...
Zigbee2MQTT:error 2020-12-28 19:58:22: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/zigbee2mqtt-1.16.2/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
    at Generator.throw (<anonymous>)
    at rejected (/zigbee2mqtt-1.16.2/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm 
ERR! zigbee2mqtt@1.16.2 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.16.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-28T18_58_22_218Z-debug.log

**Note:**
Tried with the IP : same issue.
Tried to connect though another client (Zigbee2Mqtt installed on a Debian box) : it works
No network issue : I can successfully telnet my HomeAssistant on the 1884 tcp port

**Comment by coom** [comment]
My bad, I was forgetting device: deconz in my config file ..

I close the issue. Sorry !
