### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Ferraristi** [danielwelch/hassio-zigbee2mqtt#542]
I hope someone can help me...i can't start zigbee2mqtt.
Stick is a Zigbee CC2652P Coordinator v4 USB Dongle

>test -w /dev/ttyUSB0 && echo success || echo failure

gives success back

zigbee2mqtt log
>[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[16:09:56] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[16:09:57] INFO: MQTT available, fetching server detail ...
[16:09:57] INFO: Previous config file found, checking backup
[16:09:57] INFO: Creating backup config in /config/zigbee2mqtt/.configuration.yaml.bk
[16:09:57] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:09:58] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.21.2 start
> node index.js
Zigbee2MQTT:debug 2021-10-07 16:10:04: Loaded state from file /config/zigbee2mqtt/state.json
Zigbee2MQTT:info  2021-10-07 16:10:04: Logging to console and directory: '/config/zigbee2mqtt/log/2021-10-07.16-10-02' filename: log.txt
Zigbee2MQTT:debug 2021-10-07 16:10:04: Removing old log directory '/config/zigbee2mqtt/log/2021-10-07.15-58-51'
Zigbee2MQTT:info  2021-10-07 16:10:04: Starting Zigbee2MQTT version 1.21.2 (commit #unknown)
Zigbee2MQTT:info  2021-10-07 16:10:04: Starting zigbee-herdsman (0.13.149)
Zigbee2MQTT:debug 2021-10-07 16:10:04: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6547},"serialPort":{"path":"/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0"}}
  Zigbee2MQTT:error 2021-10-07 16:15:57: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-10-07 16:15:57: Failed to start zigbee
Zigbee2MQTT:error 2021-10-07 16:15:57: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2021-10-07 16:15:57: Exiting...
Zigbee2MQTT:error 2021-10-07 16:15:57: Error: network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby
    at ZnpAdapterManager.beginCommissioning (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:347:23)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:92:17)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:63:27)
    at Controller.start (/app/lib/controller.js:116:27)
    at start (/app/index.js:95:5)''

supervisor log
>ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.5:8099 ssl:default [Connect call failed ('172.30.33.5', 8099)]

config
>data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  user: user
  password: passwd
  server: mqtt://172.30.32.2
serial:
  port: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
advanced:
  log_level: debug
  pan_id: 6547
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: true

**Comment by Ferraristi** [comment]
I found this in Mosquitto log
>1633626769: New connection from 172.30.32.2 on port 1883.
1633626769: Socket error on client <unknown>, disconnecting.
1633626834: Saving in-memory database to /data/mosquitto.db.

And i don't know what to do here....( from zigbee2mqtt log )
>Zigbee2MQTT:error 2021-10-07 19:22:38: Error: network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby

i reinstalled zigbee2mqtt new, config is now
>data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  user: user
  password: passwd
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: debug
  pan_id: 6755
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false

**Comment by Ferraristi** [comment]
I can't belive it, it is working and i did nothing....
